### ISSUE TITLE
Pass arguments to Command

### ISSUE THREAD

**Issue by michelkaeser** [auraphp/Aura.Cli#19]
Is there a way to pass arguments to the command init?

E.g. I wrote a "shell" that opens other commands - and I need pass the arguments/parameters of the shell command to the one that get's executed from within it.

Thanks :)

**Comment by pmjones** [comment]
On Jul 19, 2013, at 2:47 PM, Michel wrote:

> Is there a way to pass arguments to the command init?
> 
> E.g. I wrote a "shell" that opens other commands - and I need pass the arguments/parameters of the shell command to the one that get's executed from within it.

I'm sure there is, but I'd like to see the "shell" that you're using to open the other commands before I answer. Can you paste code here, or a link to the code?

-- pmj

**Comment by michelkaeser** [comment]
Hey! I got it working (no need for IRC session today :)).

I had to extend the Context class and allow setting `$argv` through it:

```
class ShellContext extends Context {
    public function setCustomArgv($argv) {
        $this->setArgv($argv);
    }
}
```

with prepared `$argv` like:

```
$params = $this->params;
$args = array_slice($arr, 1);
$argv = array_merge($params, $args);
```

where `$arr` is the `stdio->in()` and finally:

```
$context = new ShellContext($GLOBALS);
$context->setCustomArgv($parent[1]);

$reflection = new ReflectionClass($class."Command");
$command = $reflection->newInstanceArgs(array(
    $context,
    $parent[0]->stdio,
    new Getopt(
        new OptionFactory,
        new ExceptionFactory(
            new Translator(
                include LIB."/aura/cli/intl/en_US.php"
            )
        )
    ),
    $parent[0]->signal
));
```

and got my interactive shell :)
