### ISSUE TITLE
Options "nesting"

### ISSUE THREAD

**Issue by michelkaeser** [auraphp/Aura.Cli#20]
Hi again

If you "nest" options within other options this leads to problems.

Example: `--option="sometext -parameter"`

Parameter now will be recognized as an Aura option.

In my use case I need to enter shell commands like `hostname -f` - thus, this will fail.

Therefor text entered between "" entered right after an option should be ignored.

**Comment by pmjones** [comment]
Is this something you still feel like you really need?  I have to say I think it's outside the scope of the package as it stands now.  (It's possible that v2 might be able to support something like this.)

**Comment by michelkaeser** [comment]
Hey Jones

This is definitely something that would be great. I've seen the problem that this is "wrongly" parsed by PHP itself and would need to be "fixed" by Aura.Cli -- but I'd be more than happy if this could be made to work :)

**Comment by pmjones** [comment]
Do me a favor -- take a look at the new Getopt parser in the "develop-2" branch. I think it may solve your woes.

https://github.com/auraphp/Aura.Cli/blob/develop-2/src/Context/Getopt.php

However, I'm not sure if we can backport it to v1.  Options definition is radically different (and simplified).  In theory, you would do something like this:

```
$getopt->setOptDefs($your_defs);
$getopt->setInput($your_nested_options_string);
$getopt->parse();
$values = $getopt->getValues();
```

Let me know if that helps or not.

**Comment by pmjones** [comment]
Closing this pending a v2 release. @MaddinXx if you feel this is in error, please let me know.
