### ISSUE TITLE
Required params non-setted, not present

### ISSUE THREAD

**Issue by Grummfy** [auraphp/Aura.Cli#23]
Hello,
when we have required parameters that where not setted, the systems don't make any error. It should provide any error on hasError ...

Example :

```
$options = array(
    'action,a:',
    'module,m:'
);
$getOpt = $context->getopt($options);

// check errors
if ($getOpt->hasErrors())
{
    foreach ($getOpt->getErrors() as $error)
    {
        $stdio->errln($error->getMessage());
    }
    exit(Status::USAGE);
}
```

when I try this with _php cli.php -a test_ I have no error ....

tested on php 5.3

**Comment by pmjones** [comment]
I think the correct behavior is already in place; let me explain why.

Getopt is for _options_. They may or may not be present. So if an option is "missing", that's allowed, and not an error condition.

The "required" descriptor on the option does not mean "this option is required to be present."  It means "when present, this option must have a value."

If there is something that _must_ be passed, I suggest making it an argument, not an option.

Hope that helps; please let me know if it does not.

**Comment by Grummfy** [comment]
ok, but this precisions should be written, because it add some confusion.

thanks for you answer.

**Comment by pmjones** [comment]
That's a fair point; I'll add to the docs.  Thanks for pointing it out.

**Comment by harikt** [comment]
@pmjones I have also faced this problem about required and was confused.

Also using positional arguments means you need to make sure the argument order is same. Or is there another way to resolve this ?

I feel to anyone the require is going to get confused. I have seen the commit , still in favour of having required in options to be required and pass exception.

**Comment by Grummfy** [comment]
Perhaps we can add a new metthod that check "force required" args?
