### ISSUE TITLE
test needs the framework to run

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Cli#27]
This test here is a bit misleading because it assumes we are using the framework,
https://github.com/auraphp/Aura.Cli/blob/develop-2/tests/config/DefaultTest.php#L4
could it be that we can move this to the respective glue package?

**Comment by harikt** [comment]
Hi @cordoval that is config test.

When we look into https://github.com/auraphp/Aura.Cli/blob/develop-2/tests/bootstrap.php and https://github.com/auraphp/Aura.Cli/blob/develop-2/autoload.php , I believe people will understand.

I believe the config tests will not be there for v2 tests.

**Comment by cordoval** [comment]
then a PR removing these would be valid?

**Comment by harikt** [comment]
@cordoval I believe so. I leave the last merging rights to @pmjones here.

You can send a PR if you love :) .

**Comment by cordoval** [comment]
@pmjones is here ok thanks
