### ISSUE TITLE
getOpt->getOptions() is not accessible

### ISSUE THREAD

**Issue by bluehawk** [auraphp/Aura.Cli#31]
In 7fff85abc5 you moved `getOptions()` from `GetOpt` to `GetOptParser`

This change broke our custom build help system. (which we made before you added https://github.com/auraphp/Aura.Cli/blob/develop-2/src/Help.php). 

The primary problem is that we used $getopt->getOptions() and then looped over the options and outputted our own pretty-formatted help. As far as I am aware, there is now no way to access the getOptions() call, which has moved to GetOptParser. 

Is there a way we can access GetOptParser->getOptions() ?

**Comment by harikt** [comment]
Sorry for the trouble.

Looking at the commit you pointed out I can see 

``` php
$getopt_factory = new GetoptFactory(new GetoptParser);
```

If you have made the object like 

``` php
$getopt_parser = new GetoptParser
$getopt_factory = new GetoptFactory($getopt_parser);
$getopt_parser->getOptions()
```

Let me know if I missed something.

**Comment by bluehawk** [comment]
The trouble is that line happens inside of CliFactory. 

In other words, where previously I would have done:

```
<?php
use Aura\Cli\CliFactory;

$cli_factory = new CliFactory;
$context = $cli_factory->newContext($GLOBALS);
?>
```

(as per the documentation)

And I could have accessed:

```
// Assuming I had set some options
$options = [some array of options]
// I can access the parsed options easily
$parsed_options = $context->getopt($options)->getOptions();
```

It seems like now I would have to do something gross like the following, just so I can get access to the getopt_parser

```
<?php
use Aura\Cli\CliFactory;
use Aura\Cli\Context\Argv;
use Aura\Cli\Context\Env;
use Aura\Cli\Context\Getopt;
use Aura\Cli\Context\Server;

$cli_factory = new CliFactory;

$env    = isset($globals['_ENV'])
        ? new Env($globals['_ENV'])
        : new Env;

$server = isset($globals['_SERVER'])
        ? new Server($globals['_SERVER'])
        : new Server;

$argv   = isset($globals['argv'])
        ? new Argv($globals['argv'])
        : new Argv;

$getopt_parser = new GetoptParser;
$getopt_factory = new GetoptFactory($getopt_parser);

$context = new Context(
    $env,
    $server,
    $argv,
    $getopt_factory
);

// At this point, I have $cli_factory, $context, and can access the parsed options with:
$parsed_options = $getopt_parser->getOptions();

?>
```

And I don't even know if that will work, because getopt_factory created a new instance when I passed in the options.

**Comment by harikt** [comment]
ok, here is my suggestion, but I agree there can be a way to get the `GetOptionParser` injected to the factory . https://github.com/auraphp/Aura.Cli/blob/develop-2/src/Context/GetoptFactory.php#L40 .

``` php
$env = isset($globals['_ENV'])
        ? new Env($globals['_ENV'])
        : new Env;

$server = isset($globals['_SERVER'])
        ? new Server($globals['_SERVER'])
        : new Server;

$argv = isset($globals['argv'])
        ? new Argv($globals['argv'])
        : new Argv;
$getopt_parser = new GetoptParser(new OptionFactory);
$getopt_factory = new GetoptFactory($getopt_parser);

$context = new Context(
    $env,
    $server,
    $argv,
    $getopt_factory
);
```

Now if you check the `Context` object https://github.com/auraphp/Aura.Cli/blob/develop-2/src/Context.php#L114 it provides a getopt(array $options) method which creates an instance of https://github.com/auraphp/Aura.Cli/blob/develop-2/src/Context/Getopt.php via the factory https://github.com/auraphp/Aura.Cli/blob/develop-2/src/Context/GetoptFactory.php#L56 .

And you can see the passed options to `getopt` is set in the parser of GetOptParser ( So each instance of getopt(array($values)) changes the getopt parser options) if you are creating each time.

The below is not true.

``` php
// Assuming I had set some options
$options = [some array of options]
// I can access the parsed options easily
$parsed_options = $context->getopt($options)->getOptions();
```

But this should work.

``` php
// Assuming I had set some options
$options = [some array of options]
// I can access the parsed options easily
$First_Get_Getopt_Object = $context->getopt($options);
// take the old parser object
$options1 = $getopt_parser->getOptions();
// $options1 === $options are same
// if you do again with some different new options
$Second_Getopt_Object = $context->getopt($yournewoptions);
$options2 = $getopt_parser->getOptions();
// $options2 will be same as of $yournewoptions
```

Hope that helps. Documentation may need some fix and the way of doing this may also need some fix. We can discuss with @pmjones .

**Comment by pmjones** [comment]
@harikt thanks for attending to this in my absence.

@bluehawk we could add some getters that might alleviate your situation. E.g. a hypothetical `$parser = $context->getGetoptFactory()->getGetoptParser()` would return the GetoptParser in its current state from inside the GetoptFactory. That means `$parser->getOptions()` would reflect the most-recent options passed to the parser. Would that help at all?

**Comment by bluehawk** [comment]
I believe that would work.

**Comment by pmjones** [comment]
I will get on it right now, in a new branch for your perusal. If it works we can merge to develop-2.

**Comment by pmjones** [comment]
@bluehawk Check out the new "bluehawk-getters" branch. Usage is:

```
$options = $context->getopt_factory->getGetoptParser()->getOptions();
```

Let me know if that helps.

**Comment by harikt** [comment]
You are welcome Paul. And thanks for handling it. This is good I guess.

**Comment by bluehawk** [comment]
That worked great, thanks!

**Comment by pmjones** [comment]
Excellent! Will merge to develop-2 and kill off this branch.
