### ISSUE TITLE
Using v1 or v2

### ISSUE THREAD

**Issue by CMCDragonkai** [auraphp/Aura.Cli#32]
Should I be using v1 or v2? Has the documentation been updated to v2?

**Comment by harikt** [comment]
Hey @CMCDragonkai 

> Should I be using v1 or v2

The option is for you.  v2 released first beta-1. You can see at https://github.com/auraphp/Aura.Cli/releases . For me I feel it is good to go for v2. Just mark in composer the right version. So composer update don't update the package without your knowledge. We will try not to break anything other than any serious issues.

> Has the documentation been updated to v2?

Yes the docs are all up-to date. If you find any issues open an issue or give us a PR .

Please note that develop-2 is the v2 branch. And README.md is having the documentation.

If you are satisfied with the answers please close the issue.

Thank you.

**Comment by harikt** [comment]
Good to know that you are satisfied. ( Assumption :-) )

If you have any question feel free to mail to the google groups https://groups.google.com/d/forum/auraphp or open an issue ( opening issue will be noticed only by core developers though ).

Thanks
