### ISSUE TITLE
Exception for posix not available

### ISSUE THREAD

**Issue by agentile** [auraphp/Aura.Cli#35]
Sounds like V2 packages intend to have some level of 5.3 support. In that area some builds don't have posix_isatty function available which occurs in `Stdio::setPosix()` since error reporting is turned off, when this happens it is hard to know without step debugging, as for example `$stdio = $cliFactory->newStdio();` will just die with no output/php error. Perhaps a `function_exists` and Throwing of an exception may be warranted. 

Not sure what the Aura take is on expected support is scenarios like this, just wanted you to be aware. Thanks!

**Comment by cordoval** [comment]
is unfortunate, wish we could all move to nicer things :+1: for moving upwards on v2 aura packages

**Comment by harikt** [comment]
@agentile may be need a check http://php.net/manual/en/function.function-exists.php before https://github.com/auraphp/Aura.Cli/blob/6c0df0ee77c8cd5e73fa607e7216b9ce6c5e7ff9/src/Stdio/Handle.php#L137 .

**Comment by harikt** [comment]
@agentile pushed a PR  #36 .

Thank you for reporting it. Hope that will help in the future.

Need to wait for Paul M Jones green signal.
