### ISSUE TITLE
factory methods why not static

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Cli#37]
just voicing some concerns

why the Aura\Cli\CliFactory methods are not public static?

if they can be, will you take a PR from me doing this?

**Comment by harikt** [comment]
Considering the cli being released a 2.0.0 stable, I am not sure whether we need to change that to static.

**Comment by cordoval** [comment]
i am not talking about versions, I am talking about normal practice, I don't see why we wouldn't want to have this. @pmjones ?

**Comment by pmjones** [comment]
I get where you're coming from. Even so, as a matter of principle, I want to avoid statics in Aura. (I think we have made exactly one set of exceptions to this principle in the Aura.Html package.)

**Comment by cordoval** [comment]
I actually take my question back. https://github.com/Behat/Behat/blob/master/src/Behat/Testwork/ApplicationFactory.php#L67 All said now. no need for further discussion :blush:
