### ISSUE TITLE
* @package Aura.Cli

### ISSUE THREAD

**Issue by cordoval** [auraphp/Aura.Cli#38]
i wonder if we can remove the @package old habit :blush:  i would like to send PRs to all repos getting rid of them and also @author info if possible and redudant docblocks with the same class name when standing a lone

**Comment by pmjones** [comment]
Hi @cordoval -- not sure what you mean by @package being an old habit. The PHPDoc tools group things by @package so it still seems necessary.

**Comment by cordoval** [comment]
what do we need to group them like this? is it not already done by folder structure/namespace? This is a old habit in that regard. Namespaces did away with that. I thought at least.
