### ISSUE TITLE
Expose array of parsed CLI args

### ISSUE THREAD

**Issue by compwright** [auraphp/Aura.Cli#42]
I'm using this package in a small project, and need to access the rest of the parsed commandline arguments, since they can be dynamic.

There doesn't appear to be a way to get the entire parsed `AbstractValues::$values` array, so it would be nice if there were an `AbstractValues::getValues()` method.

It would also be nice to implement the SPL `ArrayAccess`, `SeekableIterator`, and `Countable` interfaces so that `AbstractValues` instances can be iterated just like an array.

**Comment by compwright** [comment]
FYI it is possible to work around this by creating your own `GetoptParser` instances outside of the `Context` instance:

``` php
$parser = new GetoptParser(new OptionFactory);
$parser->setOptions([]);
$parser->parseInput($context->argv->get());
$options = $parser->getValues();
```

But that's just a bit of a drag.

**Comment by pmjones** [comment]
> it would be nice if there were an AbstractValues::getValues() method.

If you want to implement that, or something like it, as a PR, I'll be happy to review.

**Comment by pmjones** [comment]
On further review, there _is_ a way to get all the values out of AbstractValues. If you call `get()` without any params, you get back the entire internal values array.

I know you have different duties these days, so let me know if you need this re-opened.
