### ISSUE TITLE
Context object unreliable

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Cli#47]
Using the example from the Aura.Cli README.md, I tried to retrieve the value of an environment variable.  It failed.  Upon debugging, I found that the $_ENV super global was empty.  The reason was because my laptop and my employer's servers all have 

```
variables_order = "GPCS"
```

in the `lynx.ini` files.  That is to say, $_ENV super global and its equivalents never get set without the "E":  http://php.net/manual/en/reserved.variables.environment.php#98113

This is apparently a common configuration these days.

Strangely, the environment variables _were_ all imported into the $_SERVER super global.  This is documented as being true whenever "S" is specified for the CGI and FastCGI SAPIs, but no mention of the CLI SAPI is made:  http://us.php.net/manual/en/ini.core.php#ini.variables-order

The only reliable way to get environment variables seems to be `getenv()`.

This is really a PHP problem, and probably a result of the CLI SAPI being a "poor stepchild" in PHP for so long.  But it seems like Aura.Cli should do its best to try to work around it.  A CLI program with environment variables is like a web application without a Document Root.

I'd provide pull requests for potential patches except at the moment, I'm not sure what the cleanest way to fix this is.

**Comment by harikt** [comment]
@cxj I don't know, does https://github.com/vlucas/phpdotenv will work perfect for .env ?

**Comment by pmjones** [comment]
@cxj I think you're right that it's a PHP problem, not Aura.Cli per se, and yet it would be good to find a workaround. The fact that they get shoved into $_SERVER is ... unexpected, at least by me. ;-)

Even so, I can't think what a good workaround would be. Maybe some form of envOrServer() to check both locations? That seems hackish and messy, though.

**Comment by cxj** [comment]
I worry about the environment values suddenly disappearing from $_SERVER with some minor point release of PHP when someone decides they don't belong there, or maybe that $_SERVER shouldn't be used by CLI programs.  Maybe I worry to much.  :-)

I'm trying to find a solution that doesn't seem hackish or messy.  It's hard, because there's so many conditions one could consider:  Is `variables_order` set?  Does it contain "S" so that $_SERVER will work in place of $_ENV?  How do we warn the user, or do we not and just document it in the library?  `getenv()` always works, but how ugly would that make the code?

I'm developing a CLI application which requires one environment variable at the moment, so I'll continue to look into the problem.

**Comment by cxj** [comment]
We could override (actually, implement in Aura\Cli\Context\Env) AbstractValues::get() so as to try `getenv()` if the global does not exist, before returning the alt value:

```
    public function get($key = null, $alt = null)
    {
        if ($key === null) {
            return $this->values;
        }

        if (array_key_exists($key, $this->values)) {
            return $this->values[$key];
        }
        else if (getenv($key)) {
            return getenv($key);
        }

        return $alt;
    }
```

**Comment by pmjones** [comment]
Good idea. Send a PR for that? With test of course. :-)

**Comment by harikt** [comment]
@cxj don't forget the `} else if {` not on the next line.

Thanks!
