### ISSUE TITLE
Positional argument help text

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Cli#48]
It would be nice to have an `Aura\Cli\Help::getHelpArguments()` formatting function in the same vein as the others, but used for describing the positional arguments.  (feature request)

**Comment by pmjones** [comment]
I agree, it would be nice. I'll have to think about how to implement that one. If you have ideas, send a PR and I'll review.

**Comment by pmjones** [comment]
Maybe this could be added to Getopt somehow, with numbers to note positional arguments (in addition to letters/words for options).

**Comment by pmjones** [comment]
No, adding it to Getopt is a non-starter.

**Comment by pmjones** [comment]
I was wrong, it's a starter. @cxj take a look at the new branch `issue-48` and commit https://github.com/auraphp/Aura.Cli/commit/86e63367c921a79fe66131a85fa193196939e6b0 .

With that, you can pass `'#argname'` or '`#argname' => 'Argument description'` as an option definition. All #-prefixed options are ignored by getopt, but the help class recognizes them and builds a default usage block.

Let me know if this is the beginning of something suitable.

**Comment by cxj** [comment]
I'm attempting to try this out, but for some reason I'm not seeing any expected output, i.e. my '#bar' argument is ignored.  This makes me think I've some configuration or something wrong.  But I'm out of mental gas to figure it out tonight.  I'll take another stab at it tomorrow if I have time.

**Comment by pmjones** [comment]
Sorry to hear about the hassle. FWIW I just added some more to the branch, specifically auto-output of the argument descriptions. Let me know how it goes for you.

**Comment by cxj** [comment]
I updated to the latest rev on the branch, and now it works as expected.  Perhaps I was expecting the wrong thing earlier.  :-p

I think the Arguments section should definitely come after the Description section in the output.  I am less sure about which order Options and Arguments should be in.  Typically Arguments are specific after Options on a command line, but someone reading the Help text might be more interested in learning what the Arguments are than the Options.  I left a comment in-line with the latest rev code to this effect as well.

**Comment by pmjones** [comment]
Easy to move the arguments below the description. I responded to your inline comment as well that I think args probably ought to be before options, seeing as arguments are actually required whereas options are not. Is that a deal-breaker for you?

**Comment by cxj** [comment]
Nope, not at all.  I agree that Options are optional and Arguments are often required.  Then it's down to psychology of where people would expect to see that information.  I'm an old Unix hand, so I've got the man page format impressed on my head.  But I'm a sample size of 1.

**Comment by pmjones** [comment]
I totally get you on the man page format stuff. I looked at man page, and at git help, output as reference points. Neither of them seems to list arguments proper in their own section, at least not that I noted. If you can point me to examples of where arguments are listed on their own, I'd be happy to review it as a point of reference.

**Comment by cxj** [comment]
I've not been able to find any in a brief search.  I'm perfectly happy having the Arguments come right after the Description.

**Comment by pmjones** [comment]
Good enough!
