### ISSUE TITLE
Slight Help text reformatting -- minor feature request

### ISSUE THREAD

**Issue by cxj** [auraphp/Aura.Cli#52]
From the "it would be nice" department...

I'd like the OPTIONS sections formatted like this:

``` php
    -f, --foo=<value>
```

instead of the current:

``` php
    -f <value>
    --foo=<value>
```

It strikes me as peculiar that I can pass a value as:

```
mycommand -f 99
mycommand --foo=99
```

But not as:

```
mycommand --foo 99
```

At least, according to the help text.

And I really ought to go figure out how to write PhpUnit tests, so that I can start sending pull requests.  I'm using PhpSpec for my own code.

**Comment by pmjones** [comment]
I tried that earlier; the problem is that with multiple-value options, the lines get really long.

**Comment by cxj** [comment]
Do you mean something like this?

``` php
    -S, --some_long_option_name=<foo|bar|baz|choose|one|of|these|values|only>
```

**Comment by pmjones** [comment]
Yes, very like.

**Comment by pmjones** [comment]
Also, regarding `-f 99`, `--foo=99`, and `--foo 99`, the idea is to reduce ambiguity in how to handle value (if --foo value is optional, should 99 be the the value for --foo, or should it be an argument value?).

**Comment by cxj** [comment]
I suspect that ambiguity is one reason why Unix command line programs starting using the '--' (double dash) to indicate end of options.  It would resolve this contrived situation:

``` sh
% touch 99
% format --f=99 99
% #ok
% format -f 99 99
% # unknown behavior
% format -f 99 -- 99
% # ah, that's what we wanted.
```

All of the possible solutions have a little smell to them, I guess.  So it's probably best to pick one compromise, document it clearly and stay consistent -- which you've already done.

**Comment by cxj** [comment]
Back to the original question, it seems (to me) that it would be a very rare case indeed where multi-value options would cause lines that were too long (i.e. would screen wrap).  But that's based solely on my personal experience.

**Comment by pmjones** [comment]
I agree it's "mostly unlikely". But then some joker is going to alias -d to --directory-stack as a multiple, and it's going to wrap, and then that joker will want automated wrapping of that single line, etc etc etc. I'd rather head that off early, primarily due to my laziness.

**Comment by pmjones** [comment]
Having said all this, if you want to provide a tested PR that formats things the way you'd prefer, I will be happy to review it. :-)

**Comment by cxj** [comment]
Sounds fair enough!  Thanks much for the feedback/discussion.

**Comment by pmjones** [comment]
Thank _you_ -- it's nice to have a civil conversation. :-)
